# name: Deploy
# on:
#   push:
#     branches: [ master ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - actions/chockout@v2

#     - uses: djnotes/github-action-ssh-docker-compose@master
#       name: Docker-Stack Remote Deployment
#       with:
#         ssh_host: ${{ secrets.SSH_HOST }}
#         ssh_private_key: ${{ secrets.EXAMPLE_COM_SSH_PRIVATE_KEY }}
#         ssh_user: ${{ secrets.EXAMPLE_COM_SSH_USER }}
#         docker_compose_prefix: example.com
#         docker_compose_down: 'true'


name: Deploy
on:
  push:
    branches: [ main ]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: chaplyk/docker-compose-remote-action@v1.1
        with:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_key: ${{ secrets.SSH_KEY }}
          compose_file: docker-compose.yml
          pull: true
          build: true
